version: 2.1

orbs:
 node: circleci/node@5.1.0

executors:
  default: # Define the executor
   docker:
    - image: circleci/node:10 # Use the desired Node.js version

jobs:
  build:
   executor: node/default
   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: Build Docker image
       command: |
        docker build -t ishika -f env/dev/Dockerfile .

    - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli

    - run:
       name: Authenticate Docker client
       command: |
        aws configure set aws_access_key_id $accesskey
        aws configure set aws_secret_access_key $secret_key
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 734411915629.dkr.ecr.us-east-1.amazonaws.com

    - run:
       name: Tag Docker image
       command: |
        docker tag ishika:latest 734411915629.dkr.ecr.us-east-1.amazonaws.com/ishika:latest

    - run:
       name: Push Docker image to AWS ECR
       command: |
        docker push 734411915629.dkr.ecr.us-east-1.amazonaws.com/ishika:latest

    - run:
       name: SSH into EC2 instance
       command: |
        ssh -o StrictHostKeyChecking=no ec2-user@13.126.123.251 'touch /home/ec2-user/innobit.txt'

workflows:
  version: 2
  build-and-deploy:
   jobs:
    - build
                                                                                                                                                                                         1,12          Top
filters:
  branches:
   only:
    - main

  
