version: 2.1

orbs:
  docker: circleci/docker@1.2.0

jobs:
  build: #can be any name you choose
    executor: docker/default

    steps:
      - checkout

        # Build Docker image
      - docker/build:
          dockerfile: Dockerfile
          image: circleci/node:10

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

filters:
  branches:
    only:
      - main

 
