version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
      
    steps:
      - checkout
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t app -f /home/innobit/circleci-demo/env/dev . 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

filters:
  branches:
    only:
      - main
