version: 2.1
orbs:
 node: circleci/node@5.1.0

executors:
  default: # Define the executor
   docker:
    - image: circleci/node:10 # Use the desired Node.js version

 

jobs:
  build:
   executer: node/default      
   steps:
    - checkout
    - setup_remote_docker
      
    # Build Docker image
    - run:
       name: Build Docker image
       command: |
        docker build -t app -f env/dev/Dockerfile . 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

filters:
  branches:
    only:
      - main
